import type { RssSource } from "./collectors/rss";

export const PRECONFIGURED_SOURCES: RssSource[] = [
  // ─── POLITICS (global) ───────────────────────────────────────────────────
  { name: "Reuters Top News", url: "https://feeds.reuters.com/reuters/topNews", category: "politics", platform: "rss" },
  { name: "Reuters Politics", url: "https://feeds.reuters.com/Reuters/PoliticsNews", category: "politics", platform: "rss" },
  { name: "AP Top News", url: "https://rsshub.app/apnews/topics/apf-topnews", category: "politics", platform: "rss" },
  { name: "BBC News", url: "https://feeds.bbci.co.uk/news/rss.xml", category: "politics", platform: "rss" },
  { name: "BBC Politics", url: "https://feeds.bbci.co.uk/news/politics/rss.xml", category: "politics", platform: "rss" },
  { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", category: "politics", platform: "rss" },
  { name: "The Guardian World", url: "https://www.theguardian.com/world/rss", category: "politics", platform: "rss" },
  { name: "The Guardian Politics", url: "https://www.theguardian.com/politics/rss", category: "politics", platform: "rss" },
  { name: "NPR News", url: "https://feeds.npr.org/1001/rss.xml", category: "politics", platform: "rss" },
  { name: "NPR Politics", url: "https://feeds.npr.org/1014/rss.xml", category: "politics", platform: "rss" },
  { name: "Politico", url: "https://rss.politico.com/politics-news.xml", category: "politics", platform: "rss" },
  { name: "The Hill", url: "https://thehill.com/news/feed/", category: "politics", platform: "rss" },
  { name: "The Atlantic Politics", url: "https://www.theatlantic.com/feed/channel/politics/", category: "politics", platform: "rss" },
  { name: "Vox Politics", url: "https://www.vox.com/rss/policy-and-politics/index.xml", category: "politics", platform: "rss" },
  { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/", category: "politics", platform: "rss" },
  { name: "Foreign Affairs", url: "https://www.foreignaffairs.com/rss.xml", category: "politics", platform: "rss" },
  { name: "Council on Foreign Relations", url: "https://www.cfr.org/rss/all", category: "politics", platform: "rss" },
  { name: "DW News", url: "https://rss.dw.com/rdf/rss-en-all", category: "politics", platform: "rss" },
  { name: "France24 English", url: "https://www.france24.com/en/rss", category: "politics", platform: "rss" },
  { name: "RFI English", url: "https://www.rfi.fr/en/rss", category: "politics", platform: "rss" },
  { name: "Euronews", url: "https://feeds.feedburner.com/euronews/en/home/", category: "politics", platform: "rss" },
  { name: "Times of India World", url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", category: "politics", platform: "rss" },
  { name: "NDTV India", url: "https://feeds.feedburner.com/NdtvNews-IndiaNews", category: "politics", language: "en", platform: "rss" },
  { name: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed", category: "politics", platform: "rss" },
  { name: "Channel News Asia", url: "https://www.channelnewsasia.com/rssfeeds/8395986", category: "politics", platform: "rss" },
  { name: "ABC News Australia", url: "https://www.abc.net.au/news/feed/45910/rss.xml", category: "politics", platform: "rss" },
  { name: "CBC News Canada", url: "https://www.cbc.ca/cmlink/rss-politics", category: "politics", platform: "rss" },

  // ─── SOUTHEAST ASIA ──────────────────────────────────────────────────────
  { name: "The Star Malaysia", url: "https://www.thestar.com.my/rss/news", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Malaysiakini", url: "https://www.malaysiakini.com/rss/all", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "Malay Mail", url: "https://www.malaymail.com/feed", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "New Straits Times", url: "https://www.nst.com.my/rss/news", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Bernama Malaysia", url: "https://www.bernama.com/en/general/rss.php", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Free Malaysia Today", url: "https://www.freemalaysiatoday.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "The Edge Malaysia", url: "https://www.theedgemarkets.com/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Straits Times Singapore", url: "https://www.straitstimes.com/global-nation/rss.xml", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Singapore CNA", url: "https://www.channelnewsasia.com/rssfeeds/8395932", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Today Online Singapore", url: "https://www.todayonline.com/rss.xml", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Jakarta Post", url: "https://www.thejakartapost.com/rss/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Kompas Indonesia", url: "https://rss.kompas.com/breakingnews", category: "southeast-asia", language: "id", platform: "rss" },
  { name: "Bangkok Post", url: "https://www.bangkokpost.com/rss/data/topstories.xml", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Philippine Inquirer", url: "https://newsinfo.inquirer.net/feed", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Philippine Star", url: "https://www.philstar.com/rss/headlines", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "VN Express Vietnam", url: "https://e.vnexpress.net/rss/news.rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Myanmar Times", url: "https://www.mmtimes.com/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Khmer Times Cambodia", url: "https://www.khmertimeskh.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },

  // ─── TECHNOLOGY ──────────────────────────────────────────────────────────
  { name: "TechCrunch", url: "https://techcrunch.com/feed/", category: "technology", platform: "rss" },
  { name: "Wired", url: "https://www.wired.com/feed/rss", category: "technology", platform: "rss" },
  { name: "The Verge", url: "https://www.theverge.com/rss/index.xml", category: "technology", platform: "rss" },
  { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/technology-lab", category: "technology", platform: "rss" },
  { name: "Hacker News", url: "https://news.ycombinator.com/rss", category: "technology", platform: "rss" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/topnews.rss", category: "technology", platform: "rss" },
  { name: "VentureBeat", url: "https://venturebeat.com/feed/", category: "technology", platform: "rss" },
  { name: "ZDNet", url: "https://www.zdnet.com/news/rss.xml", category: "technology", platform: "rss" },
  { name: "Engadget", url: "https://www.engadget.com/rss.xml", category: "technology", platform: "rss" },
  { name: "9to5Mac", url: "https://9to5mac.com/feed/", category: "technology", platform: "rss" },
  { name: "9to5Google", url: "https://9to5google.com/feed/", category: "technology", platform: "rss" },
  { name: "Android Authority", url: "https://www.androidauthority.com/feed/", category: "technology", platform: "rss" },
  { name: "Mashable Tech", url: "https://mashable.com/feeds/rss/tech", category: "technology", platform: "rss" },
  { name: "The Next Web", url: "https://thenextweb.com/feed/", category: "technology", platform: "rss" },
  { name: "ReadWrite", url: "https://readwrite.com/feed/", category: "technology", platform: "rss" },
  { name: "Protocol", url: "https://www.protocol.com/rss", category: "technology", platform: "rss" },
  { name: "CNET News", url: "https://www.cnet.com/rss/news/", category: "technology", platform: "rss" },
  { name: "PCMag", url: "https://www.pcmag.com/rss/news", category: "technology", platform: "rss" },
  { name: "Dark Reading Security", url: "https://www.darkreading.com/rss.xml", category: "technology", platform: "rss" },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", category: "technology", platform: "rss" },
  { name: "Schneier on Security", url: "https://www.schneier.com/feed/atom/", category: "technology", platform: "rss" },
  { name: "AI News", url: "https://artificialintelligence-news.com/feed/", category: "technology", platform: "rss" },
  { name: "Import AI", url: "https://importai.substack.com/feed/", category: "technology", platform: "rss" },
  { name: "Sifted EU Tech", url: "https://sifted.eu/feed/", category: "technology", platform: "rss" },
  { name: "Tech in Asia", url: "https://www.techinasia.com/feed", category: "technology", platform: "rss" },
  { name: "e27 Southeast Asia Tech", url: "https://e27.co/feed/", category: "technology", language: "en", platform: "rss" },

  // ─── BUSINESS / FINANCE ──────────────────────────────────────────────────
  { name: "Reuters Business", url: "https://feeds.reuters.com/reuters/businessNews", category: "business", platform: "rss" },
  { name: "Bloomberg Markets", url: "https://feeds.bloomberg.com/markets/news.rss", category: "business", platform: "rss" },
  { name: "Financial Times", url: "https://www.ft.com/myft/following/markets.rss", category: "business", platform: "rss" },
  { name: "WSJ Markets", url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml", category: "business", platform: "rss" },
  { name: "CNBC Business", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114", category: "business", platform: "rss" },
  { name: "CNBC Finance", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069", category: "business", platform: "rss" },
  { name: "Forbes Business", url: "https://www.forbes.com/business/feed/", category: "business", platform: "rss" },
  { name: "Fortune", url: "https://fortune.com/feed/", category: "business", platform: "rss" },
  { name: "The Economist Finance", url: "https://www.economist.com/finance-and-economics/rss.xml", category: "business", platform: "rss" },
  { name: "Seeking Alpha", url: "https://seekingalpha.com/market_currents.xml", category: "business", platform: "rss" },
  { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/", category: "business", platform: "rss" },
  { name: "Investopedia", url: "https://www.investopedia.com/feedbuilder/feed/getfeed/?feedName=rss_headline", category: "business", platform: "rss" },
  { name: "Business Insider", url: "https://www.businessinsider.com/rss", category: "business", platform: "rss" },
  { name: "Harvard Business Review", url: "https://hbr.org/rss/hbr-on-leadership", category: "business", platform: "rss" },
  { name: "McKinsey Insights", url: "https://www.mckinsey.com/insights/rss", category: "business", platform: "rss" },
  { name: "IMF News", url: "https://www.imf.org/external/np/res/rss/news.xml", category: "business", platform: "rss" },
  { name: "World Bank News", url: "https://www.worldbank.org/en/news/rss.xml", category: "business", platform: "rss" },
  { name: "Nikkei Asia Business", url: "https://asia.nikkei.com/rss/feed/business", category: "business", platform: "rss" },

  // ─── CRYPTO / WEB3 ───────────────────────────────────────────────────────
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/", category: "crypto", platform: "rss" },
  { name: "CoinTelegraph", url: "https://cointelegraph.com/rss", category: "crypto", platform: "rss" },
  { name: "Decrypt", url: "https://decrypt.co/feed", category: "crypto", platform: "rss" },
  { name: "The Block", url: "https://www.theblock.co/rss.xml", category: "crypto", platform: "rss" },
  { name: "Bitcoin Magazine", url: "https://bitcoinmagazine.com/.rss/full/", category: "crypto", platform: "rss" },
  { name: "DeFi Pulse", url: "https://defipulse.com/blog/feed/", category: "crypto", platform: "rss" },
  { name: "Blockworks", url: "https://blockworks.co/feed/", category: "crypto", platform: "rss" },
  { name: "CryptoSlate", url: "https://cryptoslate.com/feed/", category: "crypto", platform: "rss" },
  { name: "BeInCrypto", url: "https://beincrypto.com/feed/", category: "crypto", platform: "rss" },
  { name: "Cryptobriefing", url: "https://cryptobriefing.com/feed/", category: "crypto", platform: "rss" },
  { name: "NewsBTC", url: "https://www.newsbtc.com/feed/", category: "crypto", platform: "rss" },
  { name: "AMBCrypto", url: "https://ambcrypto.com/feed/", category: "crypto", platform: "rss" },

  // ─── SOCIETY / CULTURE ───────────────────────────────────────────────────
  { name: "The Guardian Society", url: "https://www.theguardian.com/society/rss", category: "society", platform: "rss" },
  { name: "NYT Opinion", url: "https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml", category: "society", platform: "rss" },
  { name: "The Atlantic", url: "https://www.theatlantic.com/feed/all/", category: "society", platform: "rss" },
  { name: "Vox", url: "https://www.vox.com/rss/index.xml", category: "society", platform: "rss" },
  { name: "Slate", url: "https://slate.com/feeds/all.rss", category: "society", platform: "rss" },
  { name: "New Yorker", url: "https://www.newyorker.com/feed/everything", category: "society", platform: "rss" },
  { name: "Salon", url: "https://www.salon.com/feed/", category: "society", platform: "rss" },
  { name: "HuffPost", url: "https://www.huffpost.com/section/front-page/feed", category: "society", platform: "rss" },
  { name: "Truthout", url: "https://truthout.org/feed/", category: "society", platform: "rss" },
  { name: "CommonDreams", url: "https://www.commondreams.org/rss.xml", category: "society", platform: "rss" },
  { name: "Intercept", url: "https://theintercept.com/feed/?lang=en", category: "society", platform: "rss" },
  { name: "ProPublica", url: "https://feeds.propublica.org/propublica/main", category: "society", platform: "rss" },

  // ─── SCIENCE / HEALTH ────────────────────────────────────────────────────
  { name: "Nature News", url: "https://www.nature.com/news.rss", category: "health", platform: "rss" },
  { name: "Science Daily", url: "https://www.sciencedaily.com/rss/top/health.xml", category: "health", platform: "rss" },
  { name: "New Scientist", url: "https://www.newscientist.com/feed/home/?cmpid=RSS", category: "health", platform: "rss" },
  { name: "Harvard Health", url: "https://www.health.harvard.edu/blog/feed", category: "health", platform: "rss" },
  { name: "Medical News Today", url: "https://www.medicalnewstoday.com/rss", category: "health", platform: "rss" },
  { name: "WebMD Health News", url: "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC", category: "health", platform: "rss" },
  { name: "Healthline", url: "https://www.healthline.com/rss/health-news", category: "health", platform: "rss" },
  { name: "STAT News", url: "https://www.statnews.com/feed/", category: "health", platform: "rss" },
  { name: "Fierce Pharma", url: "https://www.fiercepharma.com/rss/xml", category: "health", platform: "rss" },
  { name: "WHO News", url: "https://www.who.int/feeds/entity/news/en/rss.xml", category: "health", platform: "rss" },
  { name: "CDC Media", url: "https://tools.cdc.gov/api/v2/resources/media/132608.rss", category: "health", platform: "rss" },
  { name: "Phys.org", url: "https://phys.org/rss-feed/", category: "health", platform: "rss" },

  // ─── ENVIRONMENT ─────────────────────────────────────────────────────────
  { name: "The Guardian Environment", url: "https://www.theguardian.com/environment/rss", category: "environment", platform: "rss" },
  { name: "Climate Home News", url: "https://www.climatechangenews.com/feed/", category: "environment", platform: "rss" },
  { name: "Carbon Brief", url: "https://www.carbonbrief.org/feed", category: "environment", platform: "rss" },
  { name: "Yale Environment 360", url: "https://e360.yale.edu/feed.xml", category: "environment", platform: "rss" },
  { name: "Environmental Health News", url: "https://www.ehn.org/rss/", category: "environment", platform: "rss" },
  { name: "InsideClimate News", url: "https://insideclimatenews.org/feed/", category: "environment", platform: "rss" },
  { name: "DeSmog", url: "https://www.desmog.com/feed/", category: "environment", platform: "rss" },
  { name: "EcoWatch", url: "https://www.ecowatch.com/main.rss", category: "environment", platform: "rss" },
  { name: "Grist", url: "https://grist.org/feed/", category: "environment", platform: "rss" },
  { name: "Reuters Climate", url: "https://feeds.reuters.com/reuters/environment", category: "environment", platform: "rss" },
  { name: "CleanTechnica", url: "https://cleantechnica.com/feed/", category: "environment", platform: "rss" },
  { name: "Mongabay", url: "https://news.mongabay.com/feed/", category: "environment", platform: "rss" },

  // ─── SPORTS ──────────────────────────────────────────────────────────────
  { name: "ESPN Top Headlines", url: "https://www.espn.com/espn/rss/news", category: "sports", platform: "rss" },
  { name: "BBC Sport", url: "https://feeds.bbci.co.uk/sport/rss.xml", category: "sports", platform: "rss" },
  { name: "Sky Sports News", url: "https://www.skysports.com/rss/12040", category: "sports", platform: "rss" },
  { name: "The Guardian Sport", url: "https://www.theguardian.com/sport/rss", category: "sports", platform: "rss" },
  { name: "Sports Illustrated", url: "https://www.si.com/rss/si_topstories.rss", category: "sports", platform: "rss" },
  { name: "Bleacher Report", url: "https://bleacherreport.com/articles/feed", category: "sports", platform: "rss" },
  { name: "NFL News", url: "https://www.nfl.com/rss/rsslanding?searchString=news", category: "sports", platform: "rss" },
  { name: "NBA News", url: "https://www.nba.com/rss/latest_nba_news.rss", category: "sports", platform: "rss" },
  { name: "Formula 1", url: "https://www.formula1.com/content/fom-website/en/latest/all.xml", category: "sports", platform: "rss" },
  { name: "Cricinfo", url: "https://www.espncricinfo.com/rss/content/story/feeds/0.xml", category: "sports", platform: "rss" },
  { name: "The42 Ireland", url: "https://www.the42.ie/feed/", category: "sports", platform: "rss" },
  { name: "Goal Football", url: "https://www.goal.com/feeds/en/news", category: "sports", platform: "rss" },

  // ─── ENTERTAINMENT / MEDIA ───────────────────────────────────────────────
  { name: "Hollywood Reporter", url: "https://www.hollywoodreporter.com/c/news/feed/", category: "entertainment", platform: "rss" },
  { name: "Variety", url: "https://variety.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Entertainment Weekly", url: "https://ew.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Deadline Hollywood", url: "https://deadline.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Vulture", url: "https://www.vulture.com/rss/all.xml", category: "entertainment", platform: "rss" },
  { name: "IndieWire", url: "https://www.indiewire.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Rolling Stone", url: "https://www.rollingstone.com/music/music-news/feed/", category: "entertainment", platform: "rss" },
  { name: "Pitchfork", url: "https://pitchfork.com/rss/news/", category: "entertainment", platform: "rss" },
  { name: "NME Music", url: "https://www.nme.com/news/music/feed/", category: "entertainment", platform: "rss" },
  { name: "IGN Gaming", url: "https://feeds.feedburner.com/ign/all", category: "entertainment", platform: "rss" },
  { name: "Kotaku", url: "https://kotaku.com/rss", category: "entertainment", platform: "rss" },

  // ─── MEDIA / BRANDING / PR ───────────────────────────────────────────────
  { name: "AdWeek", url: "https://www.adweek.com/category/advertising/feed/", category: "media", platform: "rss" },
  { name: "Campaign Magazine", url: "https://www.campaignlive.co.uk/rss", category: "media", platform: "rss" },
  { name: "Marketing Week", url: "https://www.marketingweek.com/feed/", category: "media", platform: "rss" },
  { name: "Digiday", url: "https://digiday.com/feed/", category: "media", platform: "rss" },
  { name: "Media Post", url: "https://www.mediapost.com/rss/", category: "media", platform: "rss" },
  { name: "PRWeek", url: "https://www.prweek.com/rss", category: "media", platform: "rss" },
  { name: "Cision PR Newswire", url: "https://www.prnewswire.com/rss/news-releases-list.rss", category: "media", platform: "rss" },
  { name: "Business Wire", url: "https://feed.businesswire.com/rss/home/?rss=G1&_ga=2.234082428.1701032100.1580221538-271773452.1580221538", category: "media", platform: "rss" },
  { name: "Content Marketing Institute", url: "https://contentmarketinginstitute.com/feed/", category: "media", platform: "rss" },
  { name: "Social Media Today", url: "https://www.socialmediatoday.com/rss.xml", category: "media", platform: "rss" },
  { name: "Social Media Examiner", url: "https://www.socialmediaexaminer.com/feed/", category: "media", platform: "rss" },
  { name: "Sprout Social Insights", url: "https://sproutsocial.com/insights/feed/", category: "media", platform: "rss" },
  { name: "Buffer Blog", url: "https://buffer.com/resources/feed/", category: "media", platform: "rss" },

  // ─── ADDITIONAL POLITICS (REGIONAL) ─────────────────────────────────────
  { name: "Politico EU", url: "https://www.politico.eu/feed/", category: "politics", platform: "rss" },
  { name: "EUObserver", url: "https://euobserver.com/rss", category: "politics", platform: "rss" },
  { name: "Middle East Eye", url: "https://www.middleeasteye.net/rss.xml", category: "politics", platform: "rss" },
  { name: "Arab News", url: "https://www.arabnews.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Jerusalem Post", url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", category: "politics", platform: "rss" },
  { name: "Haaretz", url: "https://www.haaretz.com/srv/haaretz-feeds/index.xml", category: "politics", platform: "rss" },
  { name: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", category: "politics", platform: "rss" },
  { name: "The Hindu", url: "https://www.thehindu.com/feeder/default.rss", category: "politics", platform: "rss" },
  { name: "Dawn Pakistan", url: "https://www.dawn.com/feeds/home", category: "politics", platform: "rss" },
  { name: "Nigeria Daily Post", url: "https://dailypost.ng/feed/", category: "politics", platform: "rss" },
  { name: "AllAfrica", url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", category: "politics", platform: "rss" },
  { name: "Caribbean Journal", url: "https://www.caribjournal.com/feed/", category: "politics", platform: "rss" },
  { name: "LatAm Mercopress", url: "https://en.mercopress.com/rss", category: "politics", platform: "rss" },

  // ─── TECHNOLOGY (ADDITIONAL) ─────────────────────────────────────────────
  { name: "GitHub Blog", url: "https://github.blog/feed.xml", category: "technology", platform: "rss" },
  { name: "Google AI Blog", url: "https://blog.google/technology/ai/rss/", category: "technology", platform: "rss" },
  { name: "OpenAI Blog", url: "https://openai.com/blog/rss.xml", category: "technology", platform: "rss" },
  { name: "Anthropic News", url: "https://www.anthropic.com/rss.xml", category: "technology", platform: "rss" },
  { name: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml", category: "technology", platform: "rss" },
  { name: "Stack Overflow Blog", url: "https://stackoverflow.blog/feed/", category: "technology", platform: "rss" },
  { name: "Dev.to", url: "https://dev.to/feed", category: "technology", platform: "rss" },
  { name: "InfoQ", url: "https://feed.infoq.com/", category: "technology", platform: "rss" },
  { name: "Register IT", url: "https://www.theregister.com/headlines.atom", category: "technology", platform: "rss" },
  { name: "NetworkWorld", url: "https://www.networkworld.com/index.rss", category: "technology", platform: "rss" },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/feed/", category: "technology", platform: "rss" },
  { name: "Threatpost", url: "https://threatpost.com/feed/", category: "technology", platform: "rss" },
  { name: "CyberScoop", url: "https://www.cyberscoop.com/feed/", category: "technology", platform: "rss" },
  { name: "IEEE Spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", category: "technology", platform: "rss" },
  { name: "Wired UK", url: "https://www.wired.co.uk/feed/rss", category: "technology", platform: "rss" },
  { name: "Technode China", url: "https://technode.com/feed/", category: "technology", language: "en", platform: "rss" },
  { name: "KrASIA", url: "https://kr-asia.com/feed", category: "technology", platform: "rss" },
  { name: "Nikkei Asia Tech", url: "https://asia.nikkei.com/rss/feed/tech", category: "technology", platform: "rss" },

  // ─── BUSINESS (ADDITIONAL) ───────────────────────────────────────────────
  { name: "Inc Magazine", url: "https://www.inc.com/rss", category: "business", platform: "rss" },
  { name: "Fast Company", url: "https://www.fastcompany.com/latest/rss?limit=20", category: "business", platform: "rss" },
  { name: "Entrepreneur", url: "https://www.entrepreneur.com/latest.rss", category: "business", platform: "rss" },
  { name: "Quartz Business", url: "https://cms.qz.com/feed/", category: "business", platform: "rss" },
  { name: "Axios Business", url: "https://api.axios.com/feed/stream/business.rss", category: "business", platform: "rss" },
  { name: "Reuters Finance", url: "https://feeds.reuters.com/reuters/financialsector", category: "business", platform: "rss" },
  { name: "Nikkei Asia Finance", url: "https://asia.nikkei.com/rss/feed/economy", category: "business", platform: "rss" },
  { name: "BizTimes Milwaukee", url: "https://biztimes.com/feed/", category: "business", platform: "rss" },
  { name: "Crunchbase News", url: "https://news.crunchbase.com/feed/", category: "business", platform: "rss" },

  // ─── ADDITIONAL SOCIETY / EDUCATION ──────────────────────────────────────
  { name: "Chronicle of Higher Education", url: "https://www.chronicle.com/feed/section/the-faculty", category: "society", platform: "rss" },
  { name: "EdSurge", url: "https://www.edsurge.com/articles.rss", category: "society", platform: "rss" },
  { name: "Inside Higher Ed", url: "https://www.insidehighered.com/news/rss.xml", category: "society", platform: "rss" },
  { name: "Psychology Today", url: "https://www.psychologytoday.com/us/front/feed/rss.xml", category: "society", platform: "rss" },
  { name: "Pew Research", url: "https://www.pewresearch.org/feed/", category: "society", platform: "rss" },
  { name: "Brookings Institution", url: "https://www.brookings.edu/feeds/all/?topic_name=society-culture", category: "society", platform: "rss" },
  { name: "RAND Corporation", url: "https://www.rand.org/pubs/rss.xml", category: "society", platform: "rss" },

  // ─── DEFENSE / SECURITY ──────────────────────────────────────────────────
  { name: "Defense News", url: "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", category: "politics", platform: "rss" },
  { name: "Janes Defense", url: "https://www.janes.com/defence-news/rss", category: "politics", platform: "rss" },
  { name: "War on the Rocks", url: "https://warontherocks.com/feed/", category: "politics", platform: "rss" },
  { name: "Bellingcat", url: "https://www.bellingcat.com/feed/", category: "politics", platform: "rss" },
  { name: "RUSI", url: "https://rusi.org/rss.xml", category: "politics", platform: "rss" },
];

export const CATEGORIES = [...new Set(PRECONFIGURED_SOURCES.map((s) => s.category))];

export function getSourcesByCategory(category: string): RssSource[] {
  return PRECONFIGURED_SOURCES.filter((s) => s.category === category);
}

export function getAllCategories(): string[] {
  return CATEGORIES;
}
