import type { RssSource } from "./collectors/rss";

export const PRECONFIGURED_SOURCES: RssSource[] = [
  // ─── POLITICS (GLOBAL / WIRE SERVICES) ──────────────────────────────────
  { name: "Reuters Top News", url: "https://feeds.reuters.com/reuters/topNews", category: "politics", platform: "rss" },
  { name: "Reuters Politics", url: "https://feeds.reuters.com/Reuters/PoliticsNews", category: "politics", platform: "rss" },
  { name: "AP News", url: "https://rsshub.app/apnews/topics/apf-topnews", category: "politics", platform: "rss" },
  { name: "BBC News World", url: "https://feeds.bbci.co.uk/news/rss.xml", category: "politics", platform: "rss" },
  { name: "BBC Politics", url: "https://feeds.bbci.co.uk/news/politics/rss.xml", category: "politics", platform: "rss" },
  { name: "Al Jazeera English", url: "https://www.aljazeera.com/xml/rss/all.xml", category: "politics", platform: "rss" },
  { name: "The Guardian World", url: "https://www.theguardian.com/world/rss", category: "politics", platform: "rss" },
  { name: "The Guardian Politics", url: "https://www.theguardian.com/politics/rss", category: "politics", platform: "rss" },
  { name: "NPR News", url: "https://feeds.npr.org/1001/rss.xml", category: "politics", platform: "rss" },
  { name: "NPR Politics", url: "https://feeds.npr.org/1014/rss.xml", category: "politics", platform: "rss" },
  { name: "Politico", url: "https://rss.politico.com/politics-news.xml", category: "politics", platform: "rss" },
  { name: "The Hill", url: "https://thehill.com/news/feed/", category: "politics", platform: "rss" },
  { name: "The Atlantic Politics", url: "https://www.theatlantic.com/feed/channel/politics/", category: "politics", platform: "rss" },
  { name: "Vox Politics", url: "https://www.vox.com/rss/policy-and-politics/index.xml", category: "politics", platform: "rss" },
  { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/", category: "politics", platform: "rss" },
  { name: "Foreign Affairs", url: "https://www.foreignaffairs.com/rss.xml", category: "politics", platform: "rss" },
  { name: "Council on Foreign Relations", url: "https://www.cfr.org/rss/all", category: "politics", platform: "rss" },
  { name: "DW News", url: "https://rss.dw.com/rdf/rss-en-all", category: "politics", platform: "rss" },
  { name: "France 24 English", url: "https://www.france24.com/en/rss", category: "politics", platform: "rss" },
  { name: "RFI English", url: "https://www.rfi.fr/en/rss", category: "politics", platform: "rss" },
  { name: "Euronews", url: "https://feeds.feedburner.com/euronews/en/home/", category: "politics", platform: "rss" },
  { name: "South China Morning Post World", url: "https://www.scmp.com/rss/91/feed", category: "politics", platform: "rss" },
  { name: "Channel News Asia", url: "https://www.channelnewsasia.com/rssfeeds/8395986", category: "politics", platform: "rss" },
  { name: "ABC News Australia", url: "https://www.abc.net.au/news/feed/45910/rss.xml", category: "politics", platform: "rss" },
  { name: "CBC News Canada", url: "https://www.cbc.ca/cmlink/rss-politics", category: "politics", platform: "rss" },
  { name: "Politico EU", url: "https://www.politico.eu/feed/", category: "politics", platform: "rss" },
  { name: "EUObserver", url: "https://euobserver.com/rss", category: "politics", platform: "rss" },
  { name: "Middle East Eye", url: "https://www.middleeasteye.net/rss.xml", category: "politics", platform: "rss" },
  { name: "Arab News", url: "https://www.arabnews.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Jerusalem Post", url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", category: "politics", platform: "rss" },
  { name: "Times of India World", url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", category: "politics", platform: "rss" },
  { name: "The Hindu", url: "https://www.thehindu.com/feeder/default.rss", category: "politics", platform: "rss" },
  { name: "Dawn Pakistan", url: "https://www.dawn.com/feeds/home", category: "politics", platform: "rss" },
  { name: "Nikkei Asia Business", url: "https://asia.nikkei.com/rss/feed/business", category: "politics", platform: "rss" },
  { name: "Defense News", url: "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", category: "politics", platform: "rss" },
  { name: "War on the Rocks", url: "https://warontherocks.com/feed/", category: "politics", platform: "rss" },
  { name: "Bellingcat", url: "https://www.bellingcat.com/feed/", category: "politics", platform: "rss" },
  { name: "AllAfrica", url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", category: "politics", platform: "rss" },
  { name: "LatAm Mercopress", url: "https://en.mercopress.com/rss", category: "politics", platform: "rss" },
  { name: "The Wire India", url: "https://thewire.in/feed", category: "politics", platform: "rss" },
  { name: "NewsClick India", url: "https://newsclick.in/rss.xml", category: "politics", platform: "rss" },
  { name: "IOL South Africa", url: "https://www.iol.co.za/rss", category: "politics", platform: "rss" },
  { name: "Daily Maverick SA", url: "https://www.dailymaverick.co.za/feed/", category: "politics", platform: "rss" },
  { name: "The Nation Nigeria", url: "https://thenationonlineng.net/feed/", category: "politics", platform: "rss" },
  { name: "Premium Times Nigeria", url: "https://www.premiumtimesng.com/feed", category: "politics", platform: "rss" },
  { name: "Daily Post Nigeria", url: "https://dailypost.ng/feed/", category: "politics", platform: "rss" },
  { name: "CGTN English", url: "https://www.cgtn.com/subscribe/rss/section/world.do", category: "politics", platform: "rss" },
  { name: "Global Times China", url: "https://www.globaltimes.cn/rss/outbrain.xml", category: "politics", platform: "rss" },
  { name: "Straits Times World", url: "https://www.straitstimes.com/global-nation/rss.xml", category: "politics", platform: "rss" },
  { name: "UN News", url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml", category: "politics", platform: "rss" },
  { name: "Voice of America", url: "https://www.voanews.com/api/eqkiiqogg", category: "politics", platform: "rss" },
  { name: "Radio Free Asia", url: "https://www.rfa.org/english/RSS", category: "politics", platform: "rss" },
  { name: "openDemocracy", url: "https://www.opendemocracy.net/en/rss.xml", category: "politics", platform: "rss" },
  { name: "The Conversation Politics", url: "https://theconversation.com/us/politics/articles.atom", category: "politics", platform: "rss" },
  { name: "RFERL Radio Free Europe", url: "https://www.rferl.org/api/epiqriuyhfne", category: "politics", platform: "rss" },
  { name: "Middle East Monitor", url: "https://www.middleeastmonitor.com/feed/", category: "politics", platform: "rss" },

  // ─── SOUTHEAST ASIA ──────────────────────────────────────────────────────
  { name: "The Star Malaysia", url: "https://www.thestar.com.my/rss/news", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Malay Mail", url: "https://www.malaymail.com/feed", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "New Straits Times", url: "https://www.nst.com.my/rss/news", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Bernama Malaysia", url: "https://www.bernama.com/en/general/rss.php", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Free Malaysia Today", url: "https://www.freemalaysiatoday.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "The Edge Malaysia", url: "https://www.theedgemarkets.com/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Malaysiakini", url: "https://www.malaysiakini.com/rss/all", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "CNA Singapore", url: "https://www.channelnewsasia.com/rssfeeds/8395932", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Today Online Singapore", url: "https://www.todayonline.com/rss.xml", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "The Business Times SG", url: "https://www.businesstimes.com.sg/rss/all", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Jakarta Post", url: "https://www.thejakartapost.com/rss/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Kompas Indonesia", url: "https://rss.kompas.com/breakingnews", category: "southeast-asia", language: "id", platform: "rss" },
  { name: "Detik Indonesia", url: "https://rss.detik.com/index.php/detikcom", category: "southeast-asia", language: "id", platform: "rss" },
  { name: "Bangkok Post", url: "https://www.bangkokpost.com/rss/data/topstories.xml", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "The Nation Thailand", url: "https://www.nationthailand.com/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Philippine Daily Inquirer", url: "https://newsinfo.inquirer.net/feed", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Philippine Star", url: "https://www.philstar.com/rss/headlines", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Rappler Philippines", url: "https://www.rappler.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "VN Express Vietnam", url: "https://e.vnexpress.net/rss/news.rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Vietnam News", url: "https://vietnamnews.vn/rss/vn.rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Myanmar Times", url: "https://www.mmtimes.com/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Khmer Times Cambodia", url: "https://www.khmertimeskh.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Vientiane Times Laos", url: "https://www.vientianetimes.org.la/rss", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Borneo Post Malaysia", url: "https://www.theborneopost.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Sin Chew Daily", url: "https://www.sinchew.com.my/feed/", category: "southeast-asia", language: "zh", platform: "rss" },
  { name: "Nanyang Siang Pau", url: "https://www.nanyang.com/feed/", category: "southeast-asia", language: "zh", platform: "rss" },
  { name: "Astro Awani", url: "https://www.astroawani.com/feed", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "Berita Harian Malaysia", url: "https://www.bharian.com.my/rss", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "Utusan Malaysia", url: "https://www.utusan.com.my/feed/", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "Harian Metro Malaysia", url: "https://www.hmetro.com.my/rss", category: "southeast-asia", language: "ms", platform: "rss" },
  { name: "Tech in Asia", url: "https://www.techinasia.com/feed", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "e27 Southeast Asia", url: "https://e27.co/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "Deal Street Asia", url: "https://www.dealstreetasia.com/feed/", category: "southeast-asia", language: "en", platform: "rss" },
  { name: "KrASIA", url: "https://kr-asia.com/feed", category: "southeast-asia", language: "en", platform: "rss" },

  // ─── TECHNOLOGY ──────────────────────────────────────────────────────────
  { name: "TechCrunch", url: "https://techcrunch.com/feed/", category: "technology", platform: "rss" },
  { name: "Wired", url: "https://www.wired.com/feed/rss", category: "technology", platform: "rss" },
  { name: "The Verge", url: "https://www.theverge.com/rss/index.xml", category: "technology", platform: "rss" },
  { name: "Ars Technica Technology", url: "https://feeds.arstechnica.com/arstechnica/technology-lab", category: "technology", platform: "rss" },
  { name: "Hacker News", url: "https://news.ycombinator.com/rss", category: "technology", platform: "rss" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/topnews.rss", category: "technology", platform: "rss" },
  { name: "VentureBeat", url: "https://venturebeat.com/feed/", category: "technology", platform: "rss" },
  { name: "ZDNet", url: "https://www.zdnet.com/news/rss.xml", category: "technology", platform: "rss" },
  { name: "Engadget", url: "https://www.engadget.com/rss.xml", category: "technology", platform: "rss" },
  { name: "9to5Mac", url: "https://9to5mac.com/feed/", category: "technology", platform: "rss" },
  { name: "9to5Google", url: "https://9to5google.com/feed/", category: "technology", platform: "rss" },
  { name: "Android Authority", url: "https://www.androidauthority.com/feed/", category: "technology", platform: "rss" },
  { name: "Mashable Tech", url: "https://mashable.com/feeds/rss/tech", category: "technology", platform: "rss" },
  { name: "The Next Web", url: "https://thenextweb.com/feed/", category: "technology", platform: "rss" },
  { name: "CNET News", url: "https://www.cnet.com/rss/news/", category: "technology", platform: "rss" },
  { name: "PCMag News", url: "https://www.pcmag.com/rss/news", category: "technology", platform: "rss" },
  { name: "Dark Reading Security", url: "https://www.darkreading.com/rss.xml", category: "technology", platform: "rss" },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", category: "technology", platform: "rss" },
  { name: "Schneier on Security", url: "https://www.schneier.com/feed/atom/", category: "technology", platform: "rss" },
  { name: "AI News", url: "https://artificialintelligence-news.com/feed/", category: "technology", platform: "rss" },
  { name: "Sifted EU Tech", url: "https://sifted.eu/feed/", category: "technology", platform: "rss" },
  { name: "GitHub Blog", url: "https://github.blog/feed.xml", category: "technology", platform: "rss" },
  { name: "Google AI Blog", url: "https://blog.google/technology/ai/rss/", category: "technology", platform: "rss" },
  { name: "OpenAI Blog", url: "https://openai.com/blog/rss.xml", category: "technology", platform: "rss" },
  { name: "Anthropic News", url: "https://www.anthropic.com/rss.xml", category: "technology", platform: "rss" },
  { name: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml", category: "technology", platform: "rss" },
  { name: "Stack Overflow Blog", url: "https://stackoverflow.blog/feed/", category: "technology", platform: "rss" },
  { name: "Dev.to", url: "https://dev.to/feed", category: "technology", platform: "rss" },
  { name: "InfoQ", url: "https://feed.infoq.com/", category: "technology", platform: "rss" },
  { name: "The Register", url: "https://www.theregister.com/headlines.atom", category: "technology", platform: "rss" },
  { name: "NetworkWorld", url: "https://www.networkworld.com/index.rss", category: "technology", platform: "rss" },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/feed/", category: "technology", platform: "rss" },
  { name: "CyberScoop", url: "https://www.cyberscoop.com/feed/", category: "technology", platform: "rss" },
  { name: "IEEE Spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", category: "technology", platform: "rss" },
  { name: "Wired UK", url: "https://www.wired.co.uk/feed/rss", category: "technology", platform: "rss" },
  { name: "Technode China", url: "https://technode.com/feed/", category: "technology", language: "en", platform: "rss" },
  { name: "ReadWrite", url: "https://readwrite.com/feed/", category: "technology", platform: "rss" },
  { name: "SiliconANGLE", url: "https://siliconangle.com/feed/", category: "technology", platform: "rss" },
  { name: "Protocol Media", url: "https://www.protocol.com/rss", category: "technology", platform: "rss" },
  { name: "Axios Tech", url: "https://api.axios.com/feed/stream/technology.rss", category: "technology", platform: "rss" },
  { name: "MIT News Computer Science", url: "https://news.mit.edu/topic/mitcomputers-rss.xml", category: "technology", platform: "rss" },
  { name: "Stanford AI Lab", url: "https://ai.stanford.edu/blog/feed.xml", category: "technology", platform: "rss" },
  { name: "Google DeepMind Blog", url: "https://deepmind.com/blog/feed/basic/", category: "technology", platform: "rss" },
  { name: "MacroTrends Tech", url: "https://www.macrotrends.net/rss.xml", category: "technology", platform: "rss" },
  { name: "Techopedia", url: "https://www.techopedia.com/rss", category: "technology", platform: "rss" },
  { name: "TechRepublic", url: "https://www.techrepublic.com/rssfeeds/articles/", category: "technology", platform: "rss" },
  { name: "ComputerWorld", url: "https://www.computerworld.com/index.rss", category: "technology", platform: "rss" },
  { name: "InfoSecurity Magazine", url: "https://www.infosecurity-magazine.com/rss/news/", category: "technology", platform: "rss" },
  { name: "SC Magazine Security", url: "https://www.scmagazine.com/news/feed/", category: "technology", platform: "rss" },
  { name: "ThreatPost Security", url: "https://threatpost.com/feed/", category: "technology", platform: "rss" },

  // ─── BUSINESS / FINANCE ──────────────────────────────────────────────────
  { name: "Reuters Business", url: "https://feeds.reuters.com/reuters/businessNews", category: "business", platform: "rss" },
  { name: "Bloomberg Markets", url: "https://feeds.bloomberg.com/markets/news.rss", category: "business", platform: "rss" },
  { name: "WSJ US Business", url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml", category: "business", platform: "rss" },
  { name: "CNBC Business", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114", category: "business", platform: "rss" },
  { name: "CNBC Finance", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069", category: "business", platform: "rss" },
  { name: "Forbes Business", url: "https://www.forbes.com/business/feed/", category: "business", platform: "rss" },
  { name: "Fortune", url: "https://fortune.com/feed/", category: "business", platform: "rss" },
  { name: "The Economist Finance", url: "https://www.economist.com/finance-and-economics/rss.xml", category: "business", platform: "rss" },
  { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/", category: "business", platform: "rss" },
  { name: "Business Insider", url: "https://www.businessinsider.com/rss", category: "business", platform: "rss" },
  { name: "Harvard Business Review", url: "https://hbr.org/rss/hbr-on-leadership", category: "business", platform: "rss" },
  { name: "IMF News", url: "https://www.imf.org/external/np/res/rss/news.xml", category: "business", platform: "rss" },
  { name: "World Bank News", url: "https://www.worldbank.org/en/news/rss.xml", category: "business", platform: "rss" },
  { name: "Inc Magazine", url: "https://www.inc.com/rss", category: "business", platform: "rss" },
  { name: "Fast Company", url: "https://www.fastcompany.com/latest/rss?limit=20", category: "business", platform: "rss" },
  { name: "Entrepreneur", url: "https://www.entrepreneur.com/latest.rss", category: "business", platform: "rss" },
  { name: "Quartz Business", url: "https://cms.qz.com/feed/", category: "business", platform: "rss" },
  { name: "Crunchbase News", url: "https://news.crunchbase.com/feed/", category: "business", platform: "rss" },
  { name: "Reuters Finance", url: "https://feeds.reuters.com/reuters/financialsector", category: "business", platform: "rss" },
  { name: "Seeking Alpha", url: "https://seekingalpha.com/market_currents.xml", category: "business", platform: "rss" },
  { name: "McKinsey Insights", url: "https://www.mckinsey.com/insights/rss", category: "business", platform: "rss" },
  { name: "Financial Times Feeds", url: "https://www.ft.com/myft/following/markets.rss", category: "business", platform: "rss" },
  { name: "Investopedia", url: "https://www.investopedia.com/feedbuilder/feed/getfeed/?feedName=rss_headline", category: "business", platform: "rss" },
  { name: "Axios Business", url: "https://api.axios.com/feed/stream/business.rss", category: "business", platform: "rss" },
  { name: "Nikkei Asia Economy", url: "https://asia.nikkei.com/rss/feed/economy", category: "business", platform: "rss" },
  { name: "OECD Insights", url: "https://oecdinsights.org/feed/", category: "business", platform: "rss" },
  { name: "Trade Winds Shipping", url: "https://www.tradewindsnews.com/rss", category: "business", platform: "rss" },
  { name: "Supply Chain Dive", url: "https://www.supplychaindive.com/feeds/news/", category: "business", platform: "rss" },
  { name: "Retail Dive", url: "https://www.retaildive.com/feeds/news/", category: "business", platform: "rss" },
  { name: "CFO Dive", url: "https://www.cfodive.com/feeds/news/", category: "business", platform: "rss" },
  { name: "Banking Dive", url: "https://www.bankingdive.com/feeds/news/", category: "business", platform: "rss" },
  { name: "Insurance Journal", url: "https://www.insurancejournal.com/feeds/news/", category: "business", platform: "rss" },
  { name: "Real Estate News", url: "https://therealdeal.com/feed/", category: "business", platform: "rss" },

  // ─── CRYPTO / WEB3 ───────────────────────────────────────────────────────
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/", category: "crypto", platform: "rss" },
  { name: "CoinTelegraph", url: "https://cointelegraph.com/rss", category: "crypto", platform: "rss" },
  { name: "Decrypt", url: "https://decrypt.co/feed", category: "crypto", platform: "rss" },
  { name: "The Block Crypto", url: "https://www.theblock.co/rss.xml", category: "crypto", platform: "rss" },
  { name: "Bitcoin Magazine", url: "https://bitcoinmagazine.com/.rss/full/", category: "crypto", platform: "rss" },
  { name: "Blockworks", url: "https://blockworks.co/feed/", category: "crypto", platform: "rss" },
  { name: "CryptoSlate", url: "https://cryptoslate.com/feed/", category: "crypto", platform: "rss" },
  { name: "BeInCrypto", url: "https://beincrypto.com/feed/", category: "crypto", platform: "rss" },
  { name: "Crypto Briefing", url: "https://cryptobriefing.com/feed/", category: "crypto", platform: "rss" },
  { name: "NewsBTC", url: "https://www.newsbtc.com/feed/", category: "crypto", platform: "rss" },
  { name: "AMBCrypto", url: "https://ambcrypto.com/feed/", category: "crypto", platform: "rss" },
  { name: "CryptoPotato", url: "https://cryptopotato.com/feed/", category: "crypto", platform: "rss" },
  { name: "Crypto News", url: "https://cryptonews.com/news/feed/", category: "crypto", platform: "rss" },
  { name: "UseTheBitcoin", url: "https://usethebitcoin.com/feed/", category: "crypto", platform: "rss" },
  { name: "DeFi Pulse", url: "https://defipulse.com/blog/feed/", category: "crypto", platform: "rss" },
  { name: "Bankless", url: "https://newsletter.bankless.com/feed", category: "crypto", platform: "rss" },
  { name: "The Defiant", url: "https://thedefiant.io/feed", category: "crypto", platform: "rss" },
  { name: "Protos Crypto", url: "https://protos.com/feed/", category: "crypto", platform: "rss" },

  // ─── SOCIETY / CULTURE ───────────────────────────────────────────────────
  { name: "The Guardian Society", url: "https://www.theguardian.com/society/rss", category: "society", platform: "rss" },
  { name: "The Atlantic", url: "https://www.theatlantic.com/feed/all/", category: "society", platform: "rss" },
  { name: "Vox", url: "https://www.vox.com/rss/index.xml", category: "society", platform: "rss" },
  { name: "Slate", url: "https://slate.com/feeds/all.rss", category: "society", platform: "rss" },
  { name: "New Yorker", url: "https://www.newyorker.com/feed/everything", category: "society", platform: "rss" },
  { name: "HuffPost", url: "https://www.huffpost.com/section/front-page/feed", category: "society", platform: "rss" },
  { name: "Intercept", url: "https://theintercept.com/feed/?lang=en", category: "society", platform: "rss" },
  { name: "ProPublica", url: "https://feeds.propublica.org/propublica/main", category: "society", platform: "rss" },
  { name: "Pew Research Center", url: "https://www.pewresearch.org/feed/", category: "society", platform: "rss" },
  { name: "Brookings Institution", url: "https://www.brookings.edu/feeds/all/?topic_name=society-culture", category: "society", platform: "rss" },
  { name: "RAND Corporation", url: "https://www.rand.org/pubs/rss.xml", category: "society", platform: "rss" },
  { name: "Psychology Today", url: "https://www.psychologytoday.com/us/front/feed/rss.xml", category: "society", platform: "rss" },
  { name: "Salon Politics", url: "https://www.salon.com/feed/", category: "society", platform: "rss" },
  { name: "NPR Opinion", url: "https://feeds.npr.org/1003/rss.xml", category: "society", platform: "rss" },
  { name: "The Nation", url: "https://www.thenation.com/feed/?post_type=article", category: "society", platform: "rss" },
  { name: "CommonDreams", url: "https://www.commondreams.org/rss.xml", category: "society", platform: "rss" },
  { name: "Truthout", url: "https://truthout.org/feed/", category: "society", platform: "rss" },
  { name: "The Conversation US", url: "https://theconversation.com/us/articles.atom", category: "society", platform: "rss" },
  { name: "Think Progress", url: "https://archive.thinkprogress.org/feed/", category: "society", platform: "rss" },
  { name: "Jacobin", url: "https://jacobin.com/feed/", category: "society", platform: "rss" },
  { name: "Current Affairs", url: "https://www.currentaffairs.org/feed", category: "society", platform: "rss" },
  { name: "Dissent Magazine", url: "https://www.dissentmagazine.org/feed", category: "society", platform: "rss" },
  { name: "Reason Magazine", url: "https://reason.com/feed/", category: "society", platform: "rss" },
  { name: "American Conservative", url: "https://www.theamericanconservative.com/feed/", category: "society", platform: "rss" },
  { name: "Tablet Magazine", url: "https://www.tabletmag.com/sections/rss", category: "society", platform: "rss" },
  { name: "Lapham's Quarterly", url: "https://www.laphamsquarterly.org/rss.xml", category: "society", platform: "rss" },

  // ─── SCIENCE / HEALTH ────────────────────────────────────────────────────
  { name: "Science Daily Health", url: "https://www.sciencedaily.com/rss/top/health.xml", category: "health", platform: "rss" },
  { name: "Science Daily Science", url: "https://www.sciencedaily.com/rss/top/science.xml", category: "health", platform: "rss" },
  { name: "New Scientist", url: "https://www.newscientist.com/feed/home/?cmpid=RSS", category: "health", platform: "rss" },
  { name: "Harvard Health Blog", url: "https://www.health.harvard.edu/blog/feed", category: "health", platform: "rss" },
  { name: "Medical News Today", url: "https://www.medicalnewstoday.com/rss", category: "health", platform: "rss" },
  { name: "WebMD Health News", url: "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC", category: "health", platform: "rss" },
  { name: "Healthline", url: "https://www.healthline.com/rss/health-news", category: "health", platform: "rss" },
  { name: "STAT News", url: "https://www.statnews.com/feed/", category: "health", platform: "rss" },
  { name: "Fierce Pharma", url: "https://www.fiercepharma.com/rss/xml", category: "health", platform: "rss" },
  { name: "WHO News", url: "https://www.who.int/feeds/entity/news/en/rss.xml", category: "health", platform: "rss" },
  { name: "Phys.org Science", url: "https://phys.org/rss-feed/", category: "health", platform: "rss" },
  { name: "Nature News", url: "https://www.nature.com/news.rss", category: "health", platform: "rss" },
  { name: "The Lancet", url: "https://www.thelancet.com/rssfeed/lancet_online.xml", category: "health", platform: "rss" },
  { name: "BMJ News", url: "https://www.bmj.com/rss/current.xml", category: "health", platform: "rss" },
  { name: "NEJM Latest", url: "https://www.nejm.org/action/showFeed?jc=nejmoa&type=etoc&feed=rss", category: "health", platform: "rss" },
  { name: "Medscape News", url: "https://www.medscape.com/rss/allnews.xml", category: "health", platform: "rss" },
  { name: "MedPage Today", url: "https://www.medpagetoday.com/rss/headlines.xml", category: "health", platform: "rss" },
  { name: "Kaiser Health News", url: "https://khn.org/feed/", category: "health", platform: "rss" },
  { name: "JAMA Network", url: "https://jamanetwork.com/rss/site_181/67.xml", category: "health", platform: "rss" },
  { name: "Health Affairs", url: "https://www.healthaffairs.org/rss/site_3/41.xml", category: "health", platform: "rss" },
  { name: "Cell Press", url: "https://www.cell.com/rss/current.xml", category: "health", platform: "rss" },
  { name: "EurekAlert Science", url: "https://www.eurekalert.org/rss.xml", category: "health", platform: "rss" },
  { name: "Live Science", url: "https://www.livescience.com/feeds/all", category: "health", platform: "rss" },
  { name: "Space.com Science", url: "https://www.space.com/feeds/all", category: "health", platform: "rss" },
  { name: "IFLScience", url: "https://www.iflscience.com/rss", category: "health", platform: "rss" },

  // ─── ENVIRONMENT / CLIMATE ───────────────────────────────────────────────
  { name: "The Guardian Environment", url: "https://www.theguardian.com/environment/rss", category: "environment", platform: "rss" },
  { name: "Climate Home News", url: "https://www.climatechangenews.com/feed/", category: "environment", platform: "rss" },
  { name: "Carbon Brief", url: "https://www.carbonbrief.org/feed", category: "environment", platform: "rss" },
  { name: "Yale Environment 360", url: "https://e360.yale.edu/feed.xml", category: "environment", platform: "rss" },
  { name: "InsideClimate News", url: "https://insideclimatenews.org/feed/", category: "environment", platform: "rss" },
  { name: "DeSmog Climate", url: "https://www.desmog.com/feed/", category: "environment", platform: "rss" },
  { name: "EcoWatch", url: "https://www.ecowatch.com/main.rss", category: "environment", platform: "rss" },
  { name: "Grist", url: "https://grist.org/feed/", category: "environment", platform: "rss" },
  { name: "Reuters Environment", url: "https://feeds.reuters.com/reuters/environment", category: "environment", platform: "rss" },
  { name: "CleanTechnica", url: "https://cleantechnica.com/feed/", category: "environment", platform: "rss" },
  { name: "Mongabay Conservation", url: "https://news.mongabay.com/feed/", category: "environment", platform: "rss" },
  { name: "Environmental Health News", url: "https://www.ehn.org/rss/", category: "environment", platform: "rss" },
  { name: "Bloomberg Green", url: "https://feeds.bloomberg.com/bview/news.rss", category: "environment", platform: "rss" },
  { name: "E&E News Climate", url: "https://www.eenews.net/rss/climatewire", category: "environment", platform: "rss" },
  { name: "Canary Media", url: "https://www.canarymedia.com/feed.xml", category: "environment", platform: "rss" },
  { name: "Climate Signals", url: "https://www.climatesignals.org/feed", category: "environment", platform: "rss" },
  { name: "Sierra Club Magazine", url: "https://www.sierraclub.org/sierra/rss.xml", category: "environment", platform: "rss" },
  { name: "WWF News", url: "https://www.worldwildlife.org/magazine/issues/feed.rss", category: "environment", platform: "rss" },
  { name: "UNEP News", url: "https://www.unep.org/rss", category: "environment", platform: "rss" },
  { name: "GreenBiz", url: "https://www.greenbiz.com/feeds/all", category: "environment", platform: "rss" },

  // ─── SPORTS ──────────────────────────────────────────────────────────────
  { name: "ESPN Top Headlines", url: "https://www.espn.com/espn/rss/news", category: "sports", platform: "rss" },
  { name: "BBC Sport", url: "https://feeds.bbci.co.uk/sport/rss.xml", category: "sports", platform: "rss" },
  { name: "Sky Sports News", url: "https://www.skysports.com/rss/12040", category: "sports", platform: "rss" },
  { name: "The Guardian Sport", url: "https://www.theguardian.com/sport/rss", category: "sports", platform: "rss" },
  { name: "Sports Illustrated", url: "https://www.si.com/rss/si_topstories.rss", category: "sports", platform: "rss" },
  { name: "Bleacher Report", url: "https://bleacherreport.com/articles/feed", category: "sports", platform: "rss" },
  { name: "Goal Football", url: "https://www.goal.com/feeds/en/news", category: "sports", platform: "rss" },
  { name: "ESPN Cricinfo", url: "https://www.espncricinfo.com/rss/content/story/feeds/0.xml", category: "sports", platform: "rss" },
  { name: "Formula 1 News", url: "https://www.formula1.com/content/fom-website/en/latest/all.xml", category: "sports", platform: "rss" },
  { name: "Motorsport.com", url: "https://www.motorsport.com/rss/news/", category: "sports", platform: "rss" },
  { name: "Tennis World USA", url: "https://www.tennisworldusa.org/rss/news.xml", category: "sports", platform: "rss" },
  { name: "World Athletics", url: "https://www.worldathletics.org/rss/news.xml", category: "sports", platform: "rss" },
  { name: "FIA News", url: "https://www.fia.com/rss.xml", category: "sports", platform: "rss" },
  { name: "UEFA News", url: "https://www.uefa.com/rssfeed/rss.xml", category: "sports", platform: "rss" },
  { name: "NBA.com News", url: "https://www.nba.com/rss/latest_nba_news.rss", category: "sports", platform: "rss" },

  // ─── ENTERTAINMENT / MEDIA ───────────────────────────────────────────────
  { name: "Hollywood Reporter", url: "https://www.hollywoodreporter.com/c/news/feed/", category: "entertainment", platform: "rss" },
  { name: "Variety", url: "https://variety.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Entertainment Weekly", url: "https://ew.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Deadline Hollywood", url: "https://deadline.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Vulture", url: "https://www.vulture.com/rss/all.xml", category: "entertainment", platform: "rss" },
  { name: "IndieWire", url: "https://www.indiewire.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Rolling Stone Music", url: "https://www.rollingstone.com/music/music-news/feed/", category: "entertainment", platform: "rss" },
  { name: "Pitchfork", url: "https://pitchfork.com/rss/news/", category: "entertainment", platform: "rss" },
  { name: "NME Music", url: "https://www.nme.com/news/music/feed/", category: "entertainment", platform: "rss" },
  { name: "IGN Gaming", url: "https://feeds.feedburner.com/ign/all", category: "entertainment", platform: "rss" },
  { name: "Kotaku", url: "https://kotaku.com/rss", category: "entertainment", platform: "rss" },
  { name: "Screen Rant", url: "https://screenrant.com/feed/", category: "entertainment", platform: "rss" },
  { name: "Collider", url: "https://collider.com/feed/", category: "entertainment", platform: "rss" },
  { name: "The A.V. Club", url: "https://www.avclub.com/rss", category: "entertainment", platform: "rss" },
  { name: "Polygon Gaming", url: "https://www.polygon.com/rss/index.xml", category: "entertainment", platform: "rss" },
  { name: "GameSpot", url: "https://www.gamespot.com/feeds/game-news/", category: "entertainment", platform: "rss" },

  // ─── MEDIA / BRANDING / PR ───────────────────────────────────────────────
  { name: "AdWeek", url: "https://www.adweek.com/category/advertising/feed/", category: "media", platform: "rss" },
  { name: "Campaign Magazine", url: "https://www.campaignlive.co.uk/rss", category: "media", platform: "rss" },
  { name: "Marketing Week", url: "https://www.marketingweek.com/feed/", category: "media", platform: "rss" },
  { name: "Digiday", url: "https://digiday.com/feed/", category: "media", platform: "rss" },
  { name: "Media Post", url: "https://www.mediapost.com/rss/", category: "media", platform: "rss" },
  { name: "PRWeek", url: "https://www.prweek.com/rss", category: "media", platform: "rss" },
  { name: "Cision PR Newswire", url: "https://www.prnewswire.com/rss/news-releases-list.rss", category: "media", platform: "rss" },
  { name: "Business Wire", url: "https://feed.businesswire.com/rss/home/?rss=G1&_ga=2.234082428.1701032100.1580221538-271773452.1580221538", category: "media", platform: "rss" },
  { name: "Content Marketing Institute", url: "https://contentmarketinginstitute.com/feed/", category: "media", platform: "rss" },
  { name: "Social Media Today", url: "https://www.socialmediatoday.com/rss.xml", category: "media", platform: "rss" },
  { name: "Social Media Examiner", url: "https://www.socialmediaexaminer.com/feed/", category: "media", platform: "rss" },
  { name: "Nieman Lab", url: "https://www.niemanlab.org/feed/", category: "media", platform: "rss" },
  { name: "Columbia Journalism Review", url: "https://www.cjr.org/feed", category: "media", platform: "rss" },
  { name: "Press Gazette", url: "https://pressgazette.co.uk/feed/", category: "media", platform: "rss" },
  { name: "Poynter Institute", url: "https://www.poynter.org/feed/", category: "media", platform: "rss" },
  { name: "Media Decoder NYT", url: "https://mediadecoder.blogs.nytimes.com/feed/", category: "media", platform: "rss" },
  { name: "AdAge", url: "https://adage.com/rss", category: "media", platform: "rss" },
  { name: "Sprout Social", url: "https://sproutsocial.com/insights/feed/", category: "media", platform: "rss" },
  { name: "Buffer Blog", url: "https://buffer.com/resources/feed/", category: "media", platform: "rss" },
  { name: "HubSpot Blog", url: "https://blog.hubspot.com/marketing/rss.xml", category: "media", platform: "rss" },
  { name: "Neil Patel SEO", url: "https://neilpatel.com/blog/feed/", category: "media", platform: "rss" },
  { name: "Moz SEO Blog", url: "https://moz.com/blog/feed", category: "media", platform: "rss" },
  { name: "Search Engine Journal", url: "https://www.searchenginejournal.com/feed/", category: "media", platform: "rss" },
  { name: "Search Engine Land", url: "https://searchengineland.com/feed", category: "media", platform: "rss" },
  { name: "Martech.org", url: "https://martech.org/feed/", category: "media", platform: "rss" },

  // ─── AFRICA (REGIONAL) ───────────────────────────────────────────────────
  { name: "Daily Nation Kenya", url: "https://nation.africa/kenya/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "The Standard Kenya", url: "https://www.standardmedia.co.ke/rss/", category: "politics", language: "en", platform: "rss" },
  { name: "Business Daily Africa", url: "https://www.businessdailyafrica.com/rss/", category: "business", language: "en", platform: "rss" },
  { name: "East African", url: "https://www.theeastafrican.co.ke/tea/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "This Is Africa", url: "https://www.thisisafrica.me/feed/", category: "society", language: "en", platform: "rss" },
  { name: "Quartz Africa", url: "https://qz.com/africa/rss", category: "business", language: "en", platform: "rss" },
  { name: "Africa Report", url: "https://www.theafricareport.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "African Arguments", url: "https://africanarguments.org/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Pulse Ghana", url: "https://www.pulse.com.gh/rss", category: "society", language: "en", platform: "rss" },
  { name: "Ghana Web", url: "https://www.ghanaweb.com/GhanaHomePage/rss/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Vanguard Nigeria", url: "https://www.vanguardngr.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Punch Nigeria", url: "https://punchng.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "BusinessDay Nigeria", url: "https://businessday.ng/feed/", category: "business", language: "en", platform: "rss" },
  { name: "The Citizen Tanzania", url: "https://www.thecitizen.co.tz/tanzania/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Zambia Daily Mail", url: "https://www.daily-mail.co.zm/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Herald Zimbabwe", url: "https://www.herald.co.zw/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Namibian", url: "https://www.namibian.com.na/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Ethiopian Reporter", url: "https://www.thereporterethiopia.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Sudan Tribune", url: "https://sudantribune.com/spip.php?page=backend", category: "politics", language: "en", platform: "rss" },
  { name: "Ahram Online Egypt", url: "https://english.ahram.org.eg/rss.aspx", category: "politics", language: "en", platform: "rss" },
  { name: "Morocco World News", url: "https://www.moroccoworldnews.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Tunisia Live", url: "https://www.tunisia-live.net/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Jeune Afrique", url: "https://www.jeuneafrique.com/rss/", category: "politics", language: "fr", platform: "rss" },

  // ─── LATIN AMERICA ───────────────────────────────────────────────────────
  { name: "Buenos Aires Herald", url: "https://www.buenosairesherald.com/feed", category: "politics", language: "en", platform: "rss" },
  { name: "Rio Times Online Brazil", url: "https://riotimesonline.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "The Brazilian Report", url: "https://brazilian.report/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Mexico News Daily", url: "https://mexiconewsdaily.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Colombia Reports", url: "https://colombiareports.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Peru Reports", url: "https://perureports.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Tico Times Costa Rica", url: "https://ticotimes.net/feed", category: "politics", language: "en", platform: "rss" },
  { name: "Agencia EFE (English)", url: "https://www.efe.com/efe/english/portada/rss/2/", category: "politics", language: "en", platform: "rss" },
  { name: "Latin American Herald Tribune", url: "https://laht.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Folha de S.Paulo Intl", url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", category: "politics", language: "pt", platform: "rss" },
  { name: "El País América", url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada", category: "politics", language: "es", platform: "rss" },
  { name: "Clarin Argentina", url: "https://www.clarin.com/rss/clarin.xml", category: "politics", language: "es", platform: "rss" },
  { name: "La Nación Argentina", url: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/", category: "politics", language: "es", platform: "rss" },
  { name: "NACLA Latin America", url: "https://nacla.org/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Dialogo Chino", url: "https://dialogochino.net/en/feed/", category: "environment", language: "en", platform: "rss" },

  // ─── MIDDLE EAST (EXTENDED) ──────────────────────────────────────────────
  { name: "Al-Monitor", url: "https://www.al-monitor.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Turkey Agenda", url: "https://www.turkeyagenda.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Iran International", url: "https://www.iranintl.com/en/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Tehran Times", url: "https://www.tehrantimes.com/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Saudi Gazette", url: "https://saudigazette.com.sa/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Gulf News UAE", url: "https://gulfnews.com/rss", category: "politics", language: "en", platform: "rss" },
  { name: "The National UAE", url: "https://www.thenationalnews.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Jordan Times", url: "https://www.jordantimes.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Daily Star Lebanon", url: "https://www.dailystar.com.lb/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Al-Ahram Weekly", url: "https://english.ahram.org.eg/NewsContentAlterRSS/33/0/rss.aspx", category: "politics", language: "en", platform: "rss" },
  { name: "Asharq Al-Awsat", url: "https://english.aawsat.com/rss.xml", category: "politics", language: "en", platform: "rss" },

  // ─── SOUTH & EAST ASIA ───────────────────────────────────────────────────
  { name: "Economic Times India", url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms", category: "business", language: "en", platform: "rss" },
  { name: "Mint India", url: "https://www.livemint.com/rss/news", category: "business", language: "en", platform: "rss" },
  { name: "Business Standard India", url: "https://www.business-standard.com/rss/home_page_top_stories.rss", category: "business", language: "en", platform: "rss" },
  { name: "NDTV India", url: "https://feeds.feedburner.com/ndtvnews-latest", category: "politics", language: "en", platform: "rss" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Tribune Pakistan", url: "https://tribune.com.pk/feed/home", category: "politics", language: "en", platform: "rss" },
  { name: "Dhaka Tribune", url: "https://www.dhakatribune.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Daily Star Bangladesh", url: "https://www.thedailystar.net/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Colombo Gazette", url: "https://colombogazette.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "The Kathmandu Post", url: "https://kathmandupost.com/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Himalayan Times Nepal", url: "https://thehimalayantimes.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Sixth Tone China", url: "https://www.sixthtone.com/rss", category: "society", language: "en", platform: "rss" },
  { name: "Caixin China", url: "https://www.caixinglobal.com/rss/news.xml", category: "business", language: "en", platform: "rss" },
  { name: "Taiwan News", url: "https://www.taiwannews.com.tw/en/news/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Taipei Times", url: "https://www.taipeitimes.com/xml/index.rss", category: "politics", language: "en", platform: "rss" },
  { name: "Korea Herald", url: "https://www.koreaherald.com/common/rss_xml.php", category: "politics", language: "en", platform: "rss" },
  { name: "Korea JoongAng Daily", url: "https://koreajoongangdaily.joins.com/rss/news", category: "politics", language: "en", platform: "rss" },
  { name: "Japan Times", url: "https://www.japantimes.co.jp/feed/topstories/", category: "politics", language: "en", platform: "rss" },
  { name: "NHK World Japan", url: "https://www3.nhk.or.jp/rss/news/cat0.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Mainichi Japan", url: "https://mainichi.jp/rss/etc/manichi-english.rss", category: "politics", language: "en", platform: "rss" },
  { name: "Kyodo News Japan", url: "https://english.kyodonews.net/rss/all.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Pakistan Today", url: "https://www.pakistantoday.com.pk/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Tibet Post", url: "https://www.tibetpost.net/feed/", category: "politics", language: "en", platform: "rss" },

  // ─── EASTERN EUROPE / RUSSIA / CENTRAL ASIA ──────────────────────────────
  { name: "Kyiv Independent", url: "https://kyivindependent.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Kyiv Post", url: "https://www.kyivpost.com/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Warsaw Business Journal", url: "https://wbj.pl/feed/", category: "business", language: "en", platform: "rss" },
  { name: "Prague Monitor", url: "https://praguemonitor.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Budapest Business Journal", url: "https://bbj.hu/rss/", category: "business", language: "en", platform: "rss" },
  { name: "Bucharest Insider", url: "https://www.bucharestinsider.ro/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Moscow Times", url: "https://www.themoscowtimes.com/rss/news", category: "politics", language: "en", platform: "rss" },
  { name: "Meduza Russia", url: "https://meduza.io/en/rss/all", category: "politics", language: "en", platform: "rss" },
  { name: "Interfax News", url: "https://interfax.com/rss/latest/", category: "politics", language: "en", platform: "rss" },
  { name: "TASS Russia", url: "https://tass.com/rss/v2.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Eurasianet", url: "https://eurasianet.org/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Asia Times", url: "https://asiatimes.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Baltic Times", url: "https://www.baltictimes.com/news/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Sofia Globe Bulgaria", url: "https://sofiaglobe.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Emerging Europe", url: "https://emerging-europe.com/feed/", category: "business", language: "en", platform: "rss" },

  // ─── WESTERN EUROPE ──────────────────────────────────────────────────────
  { name: "Guardian UK", url: "https://www.theguardian.com/uk-news/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Independent UK", url: "https://www.independent.co.uk/news/rss", category: "politics", language: "en", platform: "rss" },
  { name: "Telegraph UK", url: "https://www.telegraph.co.uk/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Irish Times", url: "https://www.irishtimes.com/cmlink/news-1.1319192", category: "politics", language: "en", platform: "rss" },
  { name: "The Scotsman", url: "https://www.scotsman.com/news/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Die Zeit English", url: "https://newsfeed.zeit.de/politik/index", category: "politics", language: "de", platform: "rss" },
  { name: "Le Monde Diplomatique EN", url: "https://mondediplo.com/rss/", category: "politics", language: "en", platform: "rss" },
  { name: "The Local Europe", url: "https://www.thelocal.com/rss/", category: "society", language: "en", platform: "rss" },
  { name: "EurActiv", url: "https://www.euractiv.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "EU Business", url: "https://www.eubusiness.com/rss/", category: "business", language: "en", platform: "rss" },
  { name: "Handelsblatt Global", url: "https://www.handelsblatt.com/contentexport/feed/top-themen", category: "business", language: "de", platform: "rss" },
  { name: "Il Sole 24 Ore", url: "https://www.ilsole24ore.com/rss/mondo.xml", category: "business", language: "it", platform: "rss" },
  { name: "El Economista Spain", url: "https://www.eleconomista.es/rss/rss.php?categoria=portada", category: "business", language: "es", platform: "rss" },

  // ─── ENERGY / COMMODITIES ────────────────────────────────────────────────
  { name: "Oilprice.com", url: "https://oilprice.com/rss/main", category: "business", platform: "rss" },
  { name: "Energy Monitor", url: "https://www.energymonitor.ai/feed/", category: "environment", platform: "rss" },
  { name: "Bloomberg Energy", url: "https://feeds.bloomberg.com/energy/news.rss", category: "business", platform: "rss" },
  { name: "S&P Global Platts Energy", url: "https://www.spglobal.com/commodityinsights/en/rss", category: "business", platform: "rss" },
  { name: "Renew Economy", url: "https://reneweconomy.com.au/feed/", category: "environment", platform: "rss" },
  { name: "PV Magazine Solar", url: "https://www.pv-magazine.com/feed/", category: "environment", platform: "rss" },
  { name: "Wind Power Monthly", url: "https://www.windpowermonthly.com/rss", category: "environment", platform: "rss" },
  { name: "World Nuclear News", url: "https://www.world-nuclear-news.org/rss", category: "environment", platform: "rss" },
  { name: "Natural Gas Intelligence", url: "https://www.naturalgasintel.com/rss/", category: "business", platform: "rss" },
  { name: "Mining.com", url: "https://www.mining.com/feed/", category: "business", platform: "rss" },
  { name: "AgriPulse", url: "https://www.agri-pulse.com/rss.xml", category: "business", platform: "rss" },
  { name: "Reuters Energy", url: "https://feeds.reuters.com/reuters/energy", category: "business", platform: "rss" },

  // ─── DEFENSE / SECURITY ──────────────────────────────────────────────────
  { name: "Breaking Defense", url: "https://breakingdefense.com/feed/", category: "politics", platform: "rss" },
  { name: "Jane's 360 Defense", url: "https://www.janes.com/rss/headlines", category: "politics", platform: "rss" },
  { name: "The Drive Military", url: "https://www.thedrive.com/the-war-zone/rss", category: "politics", platform: "rss" },
  { name: "Stars and Stripes", url: "https://www.stripes.com/feeds/rss/home", category: "politics", platform: "rss" },
  { name: "C4ISRNET", url: "https://www.c4isrnet.com/arc/outboundfeeds/rss/?outputType=xml", category: "technology", platform: "rss" },
  { name: "Lawfare Blog", url: "https://www.lawfareblog.com/rss.xml", category: "politics", platform: "rss" },
  { name: "Just Security", url: "https://www.justsecurity.org/feed/", category: "politics", platform: "rss" },
  { name: "Cipher Brief Intelligence", url: "https://www.thecipherbrief.com/feed/", category: "politics", platform: "rss" },

  // ─── EDUCATION / ACADEMIA ────────────────────────────────────────────────
  { name: "Inside Higher Ed", url: "https://www.insidehighered.com/rss", category: "society", platform: "rss" },
  { name: "Chronicle Higher Education", url: "https://www.chronicle.com/feeds/9", category: "society", platform: "rss" },
  { name: "Times Higher Education", url: "https://www.timeshighereducation.com/feed.xml", category: "society", platform: "rss" },
  { name: "Education Week", url: "https://www.edweek.org/rss/latest-news", category: "society", platform: "rss" },
  { name: "Campus Technology", url: "https://campustechnology.com/rss-feeds/rss.ashx", category: "technology", platform: "rss" },
  { name: "Brookings Education", url: "https://www.brookings.edu/topics/education/feed", category: "society", platform: "rss" },
  { name: "RAND Education", url: "https://www.rand.org/topics/education.xml", category: "society", platform: "rss" },
  { name: "SSRN News", url: "https://www.ssrn.com/rss/SSRN_TRN_LSN.xml", category: "society", platform: "rss" },

  // ─── DEVELOPMENT / AID / HUMANITARIAN ────────────────────────────────────
  { name: "IRIN News", url: "https://www.thenewhumanitarian.org/rss.xml", category: "society", platform: "rss" },
  { name: "DevEx Development", url: "https://www.devex.com/news/rss.xml", category: "society", platform: "rss" },
  { name: "Inter Press Service", url: "https://www.ipsnews.net/feed/", category: "politics", platform: "rss" },
  { name: "Oxfam Blog", url: "https://www.oxfamamerica.org/explore/research-publications/rss.xml", category: "society", platform: "rss" },
  { name: "Human Rights Watch", url: "https://www.hrw.org/feeds/all.rss", category: "politics", platform: "rss" },
  { name: "Amnesty International", url: "https://www.amnesty.org/en/feed/", category: "politics", platform: "rss" },
  { name: "UNHCR News", url: "https://www.unhcr.org/feeds/news.xml", category: "society", platform: "rss" },
  { name: "UNICEF Press Releases", url: "https://www.unicef.org/rss/press-releases.xml", category: "society", platform: "rss" },
  { name: "UNDP News", url: "https://www.undp.org/feed.xml", category: "society", platform: "rss" },
  { name: "IMF Blog", url: "https://www.imf.org/external/np/blog/imfd/imfd.xml", category: "business", platform: "rss" },
  { name: "Food and Agriculture Org FAO", url: "https://www.fao.org/news/story-archive/en/rss", category: "environment", platform: "rss" },
  { name: "Global Voices", url: "https://globalvoices.org/feed/", category: "society", platform: "rss" },
  { name: "The Conversation Africa", url: "https://theconversation.com/africa/articles.atom", category: "society", platform: "rss" },
  { name: "Rest of World Tech", url: "https://restofworld.org/feed/latest/", category: "technology", platform: "rss" },

  // ─── LAW / GOVERNANCE / POLICY ───────────────────────────────────────────
  { name: "Law360 Legal News", url: "https://www.law360.com/rss/articles", category: "politics", platform: "rss" },
  { name: "Harvard Law Review", url: "https://harvardlawreview.org/feed/", category: "society", platform: "rss" },
  { name: "Above the Law", url: "https://abovethelaw.com/feed/", category: "politics", platform: "rss" },
  { name: "SSRN Legal Scholarship", url: "https://www.ssrn.com/rss/SSRN_TRN_LAW.xml", category: "politics", platform: "rss" },
  { name: "Center for Strategic Studies", url: "https://www.csis.org/rss.xml", category: "politics", platform: "rss" },
  { name: "Heritage Foundation", url: "https://www.heritage.org/rss.xml", category: "politics", platform: "rss" },
  { name: "Cato Institute", url: "https://www.cato.org/rss/all", category: "politics", platform: "rss" },
  { name: "Bipartisan Policy Center", url: "https://bipartisanpolicy.org/feed/", category: "politics", platform: "rss" },
  { name: "Atlantic Council", url: "https://www.atlanticcouncil.org/feed/", category: "politics", platform: "rss" },
  { name: "Carnegie Endowment", url: "https://carnegieendowment.org/publications/rss/", category: "politics", platform: "rss" },
  { name: "Wilson Center", url: "https://www.wilsoncenter.org/rss.xml", category: "politics", platform: "rss" },
  { name: "Stimson Center", url: "https://www.stimson.org/feed/", category: "politics", platform: "rss" },
  { name: "Tax Foundation", url: "https://taxfoundation.org/feed/", category: "business", platform: "rss" },
  { name: "OMB Watch", url: "https://www.pogo.org/rss/investigations.xml", category: "politics", platform: "rss" },

  // ─── MISCELLANEOUS GLOBAL ────────────────────────────────────────────────
  { name: "Axios World", url: "https://api.axios.com/feed/stream/world.rss", category: "politics", platform: "rss" },
  { name: "Axios Science", url: "https://api.axios.com/feed/stream/science.rss", category: "health", platform: "rss" },
  { name: "Axios Sports", url: "https://api.axios.com/feed/stream/sports.rss", category: "sports", platform: "rss" },
  { name: "BBC Future", url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", category: "health", platform: "rss" },
  { name: "Reuters Science", url: "https://feeds.reuters.com/reuters/scienceNews", category: "health", platform: "rss" },
  { name: "Reuters Health", url: "https://feeds.reuters.com/reuters/health", category: "health", platform: "rss" },
  { name: "AFP Relax News", url: "https://www.relaxnews.com/rss/", category: "entertainment", platform: "rss" },
  { name: "Sputnik International", url: "https://sputniknews.com/export/rss2/world/index.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Press TV Iran", url: "https://www.presstv.ir/rss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "RT International", url: "https://www.rt.com/rss/", category: "politics", language: "en", platform: "rss" },
  { name: "Xinhua World", url: "http://www.xinhuanet.com/english/rss/worldrss.xml", category: "politics", language: "en", platform: "rss" },
  { name: "Associated Press Science", url: "https://rsshub.app/apnews/topics/apf-science", category: "health", platform: "rss" },
  { name: "AP Business", url: "https://rsshub.app/apnews/topics/apf-business-economy", category: "business", platform: "rss" },
  { name: "AP Sports", url: "https://rsshub.app/apnews/topics/apf-sports", category: "sports", platform: "rss" },
  { name: "AP Entertainment", url: "https://rsshub.app/apnews/topics/apf-entertainment", category: "entertainment", platform: "rss" },
  { name: "AP Health", url: "https://rsshub.app/apnews/topics/apf-Health", category: "health", platform: "rss" },
  { name: "AP International", url: "https://rsshub.app/apnews/topics/apf-intlnews", category: "politics", platform: "rss" },

  // ─── OCEANIA / AUSTRALIA / NZ ────────────────────────────────────────────
  { name: "The Australian", url: "https://www.theaustralian.com.au/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Sydney Morning Herald", url: "https://www.smh.com.au/rss/feed.xml", category: "politics", language: "en", platform: "rss" },
  { name: "NZ Herald", url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/", category: "politics", language: "en", platform: "rss" },
  { name: "The Age Australia", url: "https://www.theage.com.au/rss/feed.xml", category: "politics", language: "en", platform: "rss" },
  { name: "ABC Australia Business", url: "https://www.abc.net.au/news/feed/51892/rss.xml", category: "business", language: "en", platform: "rss" },
  { name: "Stuff New Zealand", url: "https://www.stuff.co.nz/rss/", category: "politics", language: "en", platform: "rss" },
  { name: "Business Insider Australia", url: "https://www.businessinsider.com.au/feed", category: "business", language: "en", platform: "rss" },

  // ─── CANADA ──────────────────────────────────────────────────────────────
  { name: "Globe and Mail Canada", url: "https://www.theglobeandmail.com/arc/outboundfeeds/rss/section/canada/", category: "politics", language: "en", platform: "rss" },
  { name: "National Post Canada", url: "https://nationalpost.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "Toronto Star", url: "https://www.thestar.com/news.rss", category: "politics", language: "en", platform: "rss" },
  { name: "Vancouver Sun", url: "https://vancouversun.com/feed/", category: "politics", language: "en", platform: "rss" },
  { name: "CBC Business Canada", url: "https://www.cbc.ca/cmlink/rss-business", category: "business", language: "en", platform: "rss" },
  { name: "Financial Post Canada", url: "https://financialpost.com/feed/", category: "business", language: "en", platform: "rss" },
];

export const CATEGORIES = [...new Set(PRECONFIGURED_SOURCES.map((s) => s.category))];

export function getSourcesByCategory(category: string): RssSource[] {
  return PRECONFIGURED_SOURCES.filter((s) => s.category === category);
}

export function getAllCategories(): string[] {
  return CATEGORIES;
}
