import { Link } from "wouter";
import { LegalLayout } from "./LegalLayout";

export default function DisclaimerPage() {
  return (
    <LegalLayout
      title="Disclaimer"
      description="Important limitations on the intelligence, analytics, and AI-generated content provided by the THEA platform."
      path="/disclaimer"
      lastUpdated="July 3, 2026"
    >
      <p>
        The information and outputs provided by the THEA platform (the "Services") are intended to
        support informed decision-making. This Disclaimer explains important limitations you should
        understand before relying on them.
      </p>

      <h2>1. Informational Purposes Only</h2>
      <p>
        THEA's trend detection, sentiment analysis, alerts, and reports are provided for informational
        purposes only. They do not constitute legal, financial, political, or professional advice, and
        should not be treated as a substitute for professional judgment.
      </p>

      <h2>2. Nature of Predictive Analytics</h2>
      <p>
        THEA analyzes publicly available signals using statistical models and machine learning. These
        methods identify patterns and probabilities; they do not guarantee outcomes. Sentiment scores,
        anomaly detections, and forecasts are estimates and may not reflect actual future events.
      </p>

      <h2>3. AI-Generated Content</h2>
      <p>
        Statements, talking points, and other drafts generated by THEA are produced by automated
        systems and may contain inaccuracies or omissions. All AI-generated content must be reviewed and
        approved by a qualified human before it is published or acted upon. You are solely responsible
        for any content you choose to release.
      </p>

      <h2>4. Third-Party Sources</h2>
      <p>
        THEA aggregates data from third-party sources, including news, social platforms, and public
        feeds. We do not control and are not responsible for the accuracy, completeness, or availability
        of third-party content, and inclusion of any source does not imply endorsement.
      </p>

      <h2>5. No Warranty of Accuracy or Availability</h2>
      <p>
        While we work to provide reliable intelligence, we do not warrant that outputs will be accurate,
        complete, timely, or uninterrupted. Coverage and latency may vary by source, language, and
        region.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, THEA disclaims liability for any decisions made or
        actions taken in reliance on the Services or their outputs. Your use of the Services is at your
        own risk and subject to our{" "}
        <Link href="/terms">Terms of Service</Link>.
      </p>

      <h2>7. Contact Us</h2>
      <p>
        Questions about this Disclaimer can be directed to{" "}
        <a href="mailto:legal@thea.quest">legal@thea.quest</a>.
      </p>
    </LegalLayout>
  );
}
